---
- name: Copy collect-mysql rpm
  copy: src=files/collectd/collectd-mysql-5.5.0-2.el7.x86_64.rpm dest=/tmp

- name: install collectd-mysql rpm from local file
  yum: name=/tmp/collectd-mysql-5.5.0-2.el7.x86_64.rpm state=present

- template: 
    src=roles/collectd/templates/plugins/mysql.conf.j2
    dest=/etc/collectd.d/mysql.conf
  notify:
    - Restart Collectd
