---
- name: Add Collectd Server port in firewall
  shell:
        firewall-cmd --zone=public --add-port=25826/udp --permanent
  become: yes
  become_method: sudo
  notify:
    - Reload firewall
    
- template: 
    src=roles/collectd/templates/plugins/network-server.conf.j2 
    dest=/etc/collectd.d/network.conf
  become: yes
  become_method: sudo
  notify:
    - Restart Collectd

- action: 
    copy src=roles/collectd/templates/plugins/{{ item }} 
    dest=/etc/collectd.d/
  with_items:
    - rrdtool.conf
  become: yes
  become_method: sudo
  notify:
    - Restart Collectd

- yum: 
    name=collectd-rrdtool 
    state=latest
  become: yes
  become_method: sudo
  notify:
    - Restart Collectd
