---
# There should really be a playbook for core server setup that is seperate from
# the system deployment playbook
- name: Update ssh login banner
  hosts: all
  tasks:
      copy:
        src=files/ssh/sshd-banner
        dest=/etc/ssh/sshd-banner
        owner=root
        group=root
        mode=0644
  become: yes
  become_method: sudo

- name: Deploy Github deploy private key
  hosts: health-monitor
  tasks:
      copy:
        src=files/ssh/id_rsa.github
        dest=/home/grameen/.ssh/
        owner=grameen
        group=grameen
        mode=0600
  
- name: Deploy Github deploy public key
  hosts: health-monitor
  tasks:
      copy:
        src=files/ssh/id_rsa.github.pub
        dest=/home/grameen/.ssh/
        owner=grameen
        group=grameen
        mode=0644
  
- name: Deploy ssh connection config
  hosts: health-monitor
  tasks:
      copy:
        src=files/ssh/config
        dest=/home/grameen/.ssh/
        owner=grameen
        group=grameen
        mode=0600
  