---
# There should really be a playbook for core server setup that is seperate from
# the system deployment playbook
- name: Common Server Setup
  hosts: all
  tasks:
    - include: roles/server/tasks/all.yml

- name: Health Monitor Server Setup
  hosts: health-monitor
  tasks:
    - include: roles/server/tasks/health-monitor.yml
