---
# This playbook deploys the whole application stack in this site.  
- name: configure motech webservers 
  hosts: webservers
  remote_user: grameen
  tasks:
    - include: roles/web/tasks/webconfig.yml
  tags:
    - webconfig

- name: Deploy the Motech application and configuration
  hosts: webservers
  remote_user: grameen
  tasks:
    - include: roles/web/tasks/webconfig.yml
    - include: roles/web/tasks/main.yml
  tags:
    - motechdeploy

- name: configure and deploy the dbserver and application code
  hosts: dbservers
  remote_user: grameen
  roles:
    - db
  tags:
    - db

- name: configure and deploy keepalived
  hosts: dbservers
  remote_user: grameen
  serial: 1
  tasks:
    - include:  roles/db/tasks/keepalived.yml
  tags:
    - keep 

- name: configure and deploy activemq
  hosts: dbservers
  remote_user: grameen
  serial: 1
  tasks:
    - include:  roles/db/tasks/activemq.yml
  tags:
    - active

- name: configure and deploy dbbackupScripts in db server
  hosts: slavedb_motech
  remote_user: grameen
  serial: 1
  tasks:
   - include:  roles/db/tasks/dbbackup.yml
  tags:
   - dbbackupscript
- name: configure and deploy dbbackupScripts in db server
  hosts: slavedb_report
  remote_user: grameen
  serial: 1
  tasks:
   - include:  roles/db/tasks/dbbackup_report.yml
  tags:
   - dbbackupscript_report


- name: configure and deploy the Report Web servers
  hosts: reportwebserver
  remote_user: grameen
  roles:
    - reportweb
  tags:
    - reportweb
