---
# There should really be a playbook for core server setup that is seperate from
# the system deployment playbook
- name: Update ssh login banner
  hosts: all
  tasks:
      copy:
        src=files/sshd/sshd-banner
        dest=/etc/sshd/sshd-banner
        owner=root
        group=root
        mode=0644
  become: yes
  become_method: sudo

# This playbook deploys the whole application stack in this site.  
- name: configure motech webservers 
  hosts: webservers
  remote_user: grameen
  tasks:
    - include: roles/web/tasks/webconfig.yml
  tags:
    - webconfig

- name: Deploy the Motech application and configuration
  hosts: webservers
  remote_user: grameen
  tasks:
    - include: roles/web/tasks/webconfig.yml
    - include: roles/web/tasks/main.yml
  tags:
    - motechdeploy

- name: configure and deploy the dbserver and application code
  hosts: dbservers
  remote_user: grameen
  roles:
    - db
  tags:
    - db

- name: configure and deploy the dbserver and application code
  hosts: reportdbserver 
  remote_user: grameen
  roles:
    - reportdb
  tags:
    - reportdb

- name: configure and deploy keepalived
  hosts: dbservers
  remote_user: grameen
  serial: 1
  tasks:
    - include:  roles/db/tasks/keepalived.yml
  tags:
    - keep 

- name: configure and deploy activemq
  hosts: dbservers
  remote_user: grameen
  serial: 1
  tasks:
    - include:  roles/db/tasks/activemq.yml
  tags:
    - active
