---

- name: Copy Tomcat service file 
  template: 
      src=tomcat.service.j2
      dest=/etc/systemd/system/tomcat.service
      owner={{ ansible_ssh_user }}
      group=root
  become: yes
  become_method: sudo

- name: Copy Tomcat service configuration file 
  template: 
      src=tomcat.conf.j2
      dest=/etc/sysconfig/tomcat.conf
      owner={{ ansible_ssh_user }}
      group=root
  become: yes
  become_method: sudo

- name: Enable Tomcat on restart 
  shell: 
    "systemctl enable tomcat"
  become: yes
  become_method: sudo 
  
- name: Stop Tomcat
  shell:
    "nohup {{ ansible_env.CATALINA_HOME }}/bin/catalina.sh stop &"  

- name: "Copying Tomcat setting script"
  template: 
    src=setenv.sh.j2
    dest={{ ansible_env.CATALINA_HOME }}/bin/setenv.sh
    owner={{ ansible_ssh_user }}
    mode=0777

- name: Copying TOMCAT keystore
  copy: src={{ repo_home }}/wc_nationalmhealth.in_bundle.pfx dest="{{ ansible_env.CATALINA_HOME }}/conf/"

- name: configures server.xml
  template:
    src=server.xml.j2
    dest="{{ ansible_env.CATALINA_HOME }}/conf/server.xml"

- name: configures tomcat-users.xml
  template:
    src="tomcat-users.xml.j2"
    dest="{{ ansible_env.CATALINA_HOME }}/conf/tomcat-users.xml"

- name: Wait for Web server to Stop
  wait_for: host={{ inventory_hostname }} port=8080 state=stopped timeout=80

- name: Cleaning Bundles directory
  file: path={{ ansible_env.HOME }}/.motech/bundles state=absent

- name: making config directory  
  file: path={{ ansible_env.HOME }}/.motech/config state=directory
  
- name: Copying the motech-settings.properties configuration file
  template: 
    src="motech-settings.properties.j2"
    dest="{{ ansible_env.HOME }}/.motech/config/motech-settings.properties"

- name: Copying MOTECH WAR file
  copy: src={{ repo_home }}MOTECH/{{ motech_version }} dest={{ ansible_env.CATALINA_HOME }}/webapps/


- name: Copying the Application JAR files as mentioned in Variable Array
  copy: src=/opt/repo/NMS/ dest={{ ansible_env.HOME }}/.motech/bundles/  

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes
  become: yes
  become_method: sudo  

- name: Start firewall Service
  service: name=firewalld state=started enabled=yes
  become: yes
  become_method: sudo

- name: Add Tomcat port in Firewall
  shell:
        firewall-cmd --zone=public --add-port={{ tomcat_port }}/tcp --permanent
  become: yes
  become_method: sudo

- name: Add Tomcat HTTPS port in Firewall
  shell:
        firewall-cmd --zone=public --add-port={{ httpsport }}/tcp --permanent
  become: yes
  become_method: sudo

- name: Reload firewall 
  shell:
        firewall-cmd --reload
  become: yes
  become_method: sudo
